import { buildCtx } from "../context.ts";
import {
  activeIntentForBranch,
  writeHandoff,
  openHandoffs,
} from "../client.ts";
import { uncommittedFiles } from "../git.ts";
import { emit } from "../output.ts";

/**
 * handoff write — explicit rich handoff (called by /handoff slash command).
 */
export async function handoffWrite(args: {
  note?: string;
  blocker?: string;
  nextStep?: string;
  toAgent?: string;
}) {
  if (!args.note) {
    emit("handoff write: --note required", { ok: false });
    process.exit(2);
  }
  const ctx = await buildCtx();
  const intent = await activeIntentForBranch(ctx.db, ctx.cfg.agent_id, ctx.branchId);

  const handoff = await writeHandoff(ctx.db, {
    repoId: ctx.repoId,
    intentId: intent?.id,
    fromAgent: ctx.cfg.agent_id,
    toAgent: args.toAgent,
    branchName: ctx.branchName,
    note: args.note,
    blocker: args.blocker,
    nextStep: args.nextStep,
    uncommittedFiles: uncommittedFiles(),
    autoGenerated: false,
  });
  emit(`handoff ok — '${args.note.slice(0, 60)}...'`, { ok: true, handoff });
}

/**
 * handoff auto — called by SessionEnd hook. Quietly writes a stub handoff
 * if there's an active intent and uncommitted changes.
 */
export async function handoffAuto() {
  let ctx;
  try {
    ctx = await buildCtx();
  } catch {
    // Not in a repo or no config — silent.
    return;
  }
  const intent = await activeIntentForBranch(ctx.db, ctx.cfg.agent_id, ctx.branchId);
  if (!intent) {
    emit("auto-handoff: no active intent, skipping", { ok: false });
    return;
  }
  const uncommitted = uncommittedFiles();
  if (uncommitted.length === 0) {
    emit("auto-handoff: no uncommitted files, skipping", { ok: false });
    return;
  }

  await writeHandoff(ctx.db, {
    repoId: ctx.repoId,
    intentId: intent.id,
    fromAgent: ctx.cfg.agent_id,
    branchName: ctx.branchName,
    note: `(auto) Session ended with ${uncommitted.length} uncommitted file(s) on '${intent.title}'`,
    uncommittedFiles: uncommitted,
    autoGenerated: true,
  });
  emit(`auto-handoff ok — ${uncommitted.length} files in flight`, {
    ok: true,
    intent_id: intent.id,
    uncommitted,
  });
}

export async function handoffsList() {
  const ctx = await buildCtx();
  const handoffs = await openHandoffs(ctx.db, {
    repoId: ctx.repoId,
    toAgent: ctx.cfg.agent_id,
  });
  if (handoffs.length === 0) {
    emit("(no open handoffs for you)", { ok: true, handoffs: [] });
    return;
  }
  const lines = handoffs.map((h: any) => {
    const blocker = h.blocker ? ` [blocker: ${h.blocker}]` : "";
    return `• from ${h.from_agent} on ${h.branch_name ?? "?"}: ${h.note}${blocker}`;
  });
  emit(lines.join("\n"), { ok: true, handoffs });
}
